displayName=Creator's Kit
author=ScreteMonge
support=https://discord.gg/DSpPfC2Ebh
description=A suite of tools for creators
tags=tool,creator,content,kit,camera,export,model,animation
plugins=com.creatorskit.CreatorsPlugin
build=standard
version=2.2.0